sudo: false
addons:
  postgresql: "9.3"
language: perl
perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
env: TEST_DB_CONF=test_db_server.travis-ci.conf PGUSER=postgres
before_script:
  - make clean
  - createdb -T template1 template2
script: prove -lvr t/
